name: Build EXE and push to repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Compile to EXE
      run: |
        g++ main.cpp -o hello.exe
        mkdir build
        move hello.exe build\hello.exe

    - name: Commit and push EXE
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add build/hello.exe
        git commit -m "Add built hello.exe"
        git push
