name: Build C++ Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile with g++
      run: g++ main.cpp -o hello.exe

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: hello-windows
        path: hello.exe
