name: Build Electron App for Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo Installing Node modules...
          npm install

      - name: Install Electron Packager
        run: npm install electron-packager --save-dev

      - name: Build Windows Executable
        run: |
          npx electron-packager . t1 \
            --platform=win32 \
            --arch=x64 \
            --out=dist \
            --overwrite \
            --executable-name=t1

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-windows-build
          path: dist/
